### ISSUE TITLE
GoogleUpdate.exe alway say: Installation failed. Please try again.

### ISSUE THREAD

**Issue by quyen194** [Crystalnix/omaha#17]
I use this command
GoogleUpdate.exe /install "appguid={17401844-69F4-4329-A37D-047EC84B3627}&appname=BChrome&needsadmin=False&lang=en"
Almost thing go fine, installer is download and run well, after finished, BChrome Installer (Omaha Client) say "Installation failed. Please try again." "Show me help for this issue"
Thanks for help ^^

**Comment by shashkin** [comment]
https://github.com/Crystalnix/omaha/wiki/Application-registration
