### ISSUE TITLE
Error message from ViaSatUpdate.exe

### ISSUE THREAD

**Issue by debinzhang** [Crystalnix/omaha#21]
One of our testers reported this:

"I had chromium installed and tried to install sparrow. This resulted in some confusion. I then tried to uninstall sparrow and it also uninstalled chromium."

Looks like chromium and sparrow are stepping on each other. The test got the following error message:
![capture](https://cloud.githubusercontent.com/assets/9803914/6970966/22e9e1ec-d947-11e4-9ce7-808d9126ed3c.JPG)

Since Sparrow is totally separated from Chromium, should we remove this assert checking?

**Comment by shashkin** [comment]
I agree, it looks like this assertion is not needed.
Removed with 7843a08cce654aa8ba280b2c89d2eb4e7049734b
