### ISSUE TITLE
Omaha client not downloading mini-installer from correct omaha server

### ISSUE THREAD

**Issue by shashkin** [Crystalnix/omaha#24]
@chadgoss wrote:

> - create two omaha servers

> To reproduce, from the same PC:

> - use metainstaller pointed at first omaha server to download browser miniinstaller from first omaha server
> - uninstall browser
> - use metainstaller pointed at second omaha server to download miniinstaller from second. The metainstaller will not go to the second omaha-server, it will download from the first.

(moved from https://github.com/Crystalnix/omaha-server/issues/61)

**Comment by shashkin** [comment]
Hi @chadgoss,

First of all, could you please clarify what do you mean by "two metainstallers pointing to different servers"?
Omaha server URL is hardcoded into Omaha client code, and every metainstaller is the wrapper around the installer of Omaha client, so I assume you had two different builds of Omaha client and you created one metainstaller from one build and the other metainstaller from the other build.
Am I right?

Also, am I right that these two Omaha client builds have the same version number and the only difference between them is the server URL?

If everything above is correct, then I think the following happened:

- you ran the 1st metainstaller to install browser
  - at first step, metainstaller tries to install Omaha client into the system
    - you probably had no Omaha client installed so metainstaller installed 1st Omaha client (pointing to 1st server) into the system
  - after that metainstaller launches installed Omaha client to download and install browser
- you uninstalled browser
  - this doesn't cause uninstalling of Omaha client immediately. Omaha client will still be in the system until the next start of its worker process. When worker process starts, it checks whether there are any apps managed by Omaha, and if there is no any, it removes Omaha client from the system.
- you ran the 2nd metainstaller and I think you did it before Omaha client worker process removed the previously installed client from your machine
  - as before, at first step, metainstaller tries to install Omaha client into the system
    - the 1st Omaha client was still in the system and it most probably had the same version number as the 2nd one, so 2nd metainstaller thinks that 2nd Omaha client is already installed into the system
  - after that metainstaller launches installed Omaha client (which is still the 1st Omaha client pointing to the 1st server) to download and install browser.

I can suggest several ways to work around this situation:

1. After browser is uninstalled, wait until Omaha client worker process wakes up and removed Omaha client from the system. If we're talking about `viasat` branch, this will take up to 30 minutes.
2. After browser is uninstalled, open Task Scheduler and force run `...UA` scheduled task.
3. After browser is uninstalled, manually delete Omaha client from the system:
  1. Remove tasks from Task Scheduler
  2. Remove Omaha registry path
  3. Delete Omaha client files from the disk

**Comment by chadgoss** [comment]
Hi
Thanks for the detailed response, what you are saying makes sense.

I don’t think this is a situation we’ll see in production since it will be rare to switch Omaha-servers. We are working around this in test by having dedicated CPEs for each Omaha-server
Thanks again!
-chad
