### ISSUE TITLE
Omaha Client don't  update itself

### ISSUE THREAD

**Issue by quyen194** [Crystalnix/omaha#29]
I try upload a new version (build) of GoogleUpdateSetup.exe to omaha server, stable channel, but omaha client didn't download and update itself :(
How to do that? or problem in omaha server?
I using your omaha server project, Crystalnix

I saw that it did download but how to applytag to GoogleUpdateSetup.exe to run with commandline:
GoogleUpdateSetup.exe  /update

Thanks for your help

**Comment by shashkin** [comment]
You don't need to apply tag to `GoogleUpdateSetup.exe` in case of Omaha client self-update.

All you need to do is the following:
1. Upload new version with higher version number to the server
2. Make sure you're using `stable` channel. Omaha client uses `stable` channel only for self-updates.
3. Add the action for `update` event with `/update` arguments

**Comment by quyen194** [comment]
AWESOME!!!!!!!!
YOU ARE THE BEST ^^

**Comment by quyen194** [comment]
I have a small question, i saw a address in const_addresses.h
const TCHAR* const kUrlUsageStatsReport =
    _T("http://clients5.") COMPANY_DOMAIN _T("/tbproxy/usagestats");

But I see that your omaha server not provide an api for it. So what need to do?
Thanks
