### ISSUE TITLE
How to sign file using installed Certificate instead pfx file

### ISSUE THREAD

**Issue by namtb49** [Crystalnix/omaha#31]
So, I want to developt our update solution based on Omaha protocol (and this source code, respectly) to allow live-update for our customer. After several times try to tangle and digged into this source code and all document related, final I've applied Omaha update solution to my application successful. Every things seem tobe OK, and my software update nicely, btw still minor problem to hinder for the deployment process.
After upload update version to some download site and forum for trial purpose, some customer complaint that, when they download this update setup, some common web browser (such as IE or Chrome) warning they about risk security problem. After some research, I knew that because my update software was signed by test certificate (pair with download source), not by Trusted cert, so this may be lead to problem, and more seriously, this may be blocked by some Antivirus or System Protection software.

I've read in all source and script related to signing process and found that this using signtool utilites from Window SDK to sign all exe and dll file with the pfx/ cert file pair in building process. And to solve this non-trusted problem, it must be to replace these with the suitable file. And according MSDN tutorial page, I knew signtool can be using with many option, one of this is pass input param point to installed Cert has been register by Window system, which I have got from legacy project . And, because every thing have in startup step, so we want to build update software with this preinstall cert, without refund to buy the precious Global key.

So could I apply this signing approach with omaha source code, and how could achive this. I've seen in main scons file has some block of code related setup input param to call signtool utilite, but it may be lead to recursive change to many script and py file in other module.

**Comment by thekondr** [comment]
Hi @namtb49,

You can try to export installed certificate into pfx file.

Please check this [article](https://www.sslshopper.com/move-or-copy-an-ssl-certificate-from-a-windows-server-to-another-windows-server.html).

**Comment by namtb49** [comment]
Sorry, may be I didn't describe my problem clearly in prev post. 
In more details, I get this installed cert from my owned USB token device, that producer dont cater any cert file from these deal. After install this token to my Window PC, I have installed cert that may be use to sign and verify file before public. This cert can be view from cert management  snapin Window program.
With single file I can use this device to sign and verify file with signtool util, by spectific input param to installed cert that belong to that USB token, and input the correct password for next prompt window from signing process step. It's work, and now I plan to sign all file in omaha build result using this device. But with Omaha script process, I haven't  found properly way to pass this cert in right way

**Comment by thekondr** [comment]
Resolved in Google Omaha

https://github.com/google/omaha/issues/77
