### ISSUE TITLE
Out-Of-Process Crash_report

### ISSUE THREAD

**Issue by synapsy88** [Crystalnix/omaha#37]
Hi, 
if my install.exe compiled with go build install.go fails install/update how to report this failure to crash_report server ? 

Can you send me an example ? 

Thanks

**Comment by kyakovenko** [comment]
Hello synapsy88,

Sorry, but Omaha client doesn't send any crash reports to a server. In general, Omaha client is only responsible for updates and nothing else. If you want to send crash reports, I would recommend you to look at CrashPad. You can find more information about it by the following links:

https://chromium.googlesource.com/crashpad/crashpad
https://chromium.googlesource.com/crashpad/crashpad/+/master//doc/developing.md

Best regards,
Kirill
